In [1]:
pip install theano

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\91789\Anaconda3\python.exe -m pip install --upgrade pip' command.


In [2]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\91789\Anaconda3\python.exe -m pip install --upgrade pip' command.


In [3]:
conda update --all

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\91789\Anaconda3


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    anaconda-navigator-1.10.0  |           py37_0         4.9 MB
    backports.functools_lru_cache-1.6.1|     pyhd3eb1b0_0          12 KB
    backports.tempfile-1.0     |     pyhd3eb1b0_1          11 KB
    conda-build-3.21.4         |   py37haa95532_0         550 KB
    xmltodict-0.12.0           |             py_0          14 KB
    ------------------------------------------------------------
                                           Total:         5.5 MB

The following NEW packages will be INSTALLED:

  xmltodict          pkgs/main/noarch::xmltodict-0.12.0-py_0

The following packages will be UPDATED:

  anaconda-navigator                           1.9.7-py37_0 --> 1.10.0-py37_0
  conda-build                                 3.18.9

DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\91789\Anaconda3', env_name: 'None', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\91789\Anaconda3\pythonw.exe, args are ['C:\\Users\\91789\\Anaconda3\\cwp.py', 'C:\\Users\\91789\\Anaconda3', 'C:\\Users\\91789\\Anaconda3\\pythonw.exe', 'C:\\Users\\91789\\Anaconda3\\Scripts\\anaconda-navigator-script.py']
DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\91789\Anaconda3', env_name: 'None', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\91789\Anaconda3\pythonw.exe, args are ['C:\\Users\\91789\\Anaconda3\\cwp.py', 'C:\\Users\\91789\\Anaconda3', 'C:\\Users\\91789\\Anaconda3\\pythonw.exe', 'C:\\Users\\91789\\Anaconda3\\Scripts\\anaconda-navigator-script.py']
DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\917

In [58]:
# import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [59]:
# import the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
# X = independent variables
X = dataset.iloc[:, 3:13].values
# y = target variable
y = dataset.iloc[:, 13].values

In [60]:
#print independent variables
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [61]:
# Encode Categorical data Here it is Country and Name
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [62]:
print(X)
# All independent variables are of float64 type

[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]


In [63]:
X = X[:, 1:]

In [64]:
# Splitting the dataset into Training and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [65]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [66]:
# Building the ANN
import keras 
from keras.models import Sequential
from keras.layers import Dense

# Initializing the ANN
classifier = Sequential()
# Add Input layer and Hidden layer
classifier.add(Dense(output_dim = 6, init='uniform', activation='relu', input_dim=9))
# Add 2nd Hidden layer
classifier.add(Dense(output_dim = 6, init='uniform', activation='relu'))
# Add output layer
classifier.add(Dense(output_dim = 1, init='uniform', activation='sigmoid'))

C:\Users\91789\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=9, units=6, kernel_initializer="uniform")`
  if __name__ == '__main__':
C:\Users\91789\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  # This is added back by InteractiveShellApp.init_path()
C:\Users\91789\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  del sys.path[0]


In [67]:
# Compiling the ANN
classifier.compile(optimizer='adam', loss ='binary_crossentropy', metrics=['accuracy'])

In [68]:
# Fit ANN to training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

C:\Users\91789\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 10s 1ms/step - loss: 0.4826 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 11s 1ms/step - loss: 0.4325 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 11s 1ms/step - loss: 0.4259 - accuracy: 0.7980
Epoch 4/100
8000/8000 [==============================] - 11s 1ms/step - loss: 0.4219 - accuracy: 0.8230
Epoch 5/100
8000/8000 [==============================] - 11s 1ms/step - loss: 0.4188 - accuracy: 0.8274
Epoch 6/100
8000/8000 [==============================] - 11s 1ms/step - loss: 0.4165 - accuracy: 0.8300
Epoch 7/100
8000/8000 [==============================] - 11s 1ms/step - loss: 0.4145 - accuracy: 0.8329
Epoch 8/100
8000/8000 [==============================] - 11s 1ms/step - loss: 0.4124 - accuracy: 0.8311
Epoch 9/100
8000/8000 [==============================] - 11s 1ms/step - loss: 0.4115 - accuracy: 0.8321
Epoch 10/100
8000/8000 [==============================] - 11s 1m

In [52]:
# Predicting the test set results
y_pred = classifier.predict(X_test)
# Normalizing to True and False
y_pred = (y_pred>0.5)

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [54]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1536,   59],
       [ 260,  145]], dtype=int64)

In [55]:
# Accuracy on the test set
(1536 + 145)/2000

0.8405